"""PyQt6 frequency-sweep dialog for OpenMoRFeus."""

from __future__ import annotations

from PyQt6.QtCore import (
    QObject,
    QRunnable,
    QThreadPool,
    pyqtSignal,
    pyqtSlot,
)
from PyQt6.QtGui import QCloseEvent
from PyQt6.QtWidgets import (
    QCheckBox,
    QDialog,
    QDoubleSpinBox,
    QFormLayout,
    QGroupBox,
    QHBoxLayout,
    QLabel,
    QMessageBox,
    QProgressBar,
    QPushButton,
    QSpinBox,
    QVBoxLayout,
    QWidget,
)

from .sweep import (
    SweepControl,
    SweepPlan,
    SweepProgress,
    SweepResult,
    execute_sweep,
)
from .writable import (
    MAX_FREQUENCY_HZ,
    MIN_FREQUENCY_HZ,
)


def format_duration(seconds: float) -> str:
    """Format a duration for the sweep summary."""

    if seconds < 60:
        return f"{seconds:.2f} s"

    minutes, remaining_seconds = divmod(
        seconds,
        60,
    )

    if minutes < 60:
        return (
            f"{int(minutes)} min "
            f"{remaining_seconds:.1f} s"
        )

    hours, remaining_minutes = divmod(
        int(minutes),
        60,
    )

    return (
        f"{hours} h "
        f"{remaining_minutes} min "
        f"{remaining_seconds:.0f} s"
    )


class SweepWorkerSignals(QObject):
    """Signals generated by the background sweep."""

    progress = pyqtSignal(object)
    succeeded = pyqtSignal(object)
    failed = pyqtSignal(str)
    finished = pyqtSignal()


class SweepWorker(QRunnable):
    """Execute one sweep outside the graphical thread."""

    def __init__(
        self,
        plan: SweepPlan,
        connection_parameters: dict[
            str,
            int | float,
        ],
        control: SweepControl,
    ):
        super().__init__()

        self._plan = plan
        self._connection_parameters = dict(
            connection_parameters
        )
        self._control = control
        self.signals = SweepWorkerSignals()

    @pyqtSlot()
    def run(self) -> None:
        try:
            result = execute_sweep(
                self._plan,
                control=self._control,
                on_progress=(
                    self.signals.progress.emit
                ),
                **self._connection_parameters,
            )
        except Exception as exc:
            self.signals.failed.emit(
                f"{type(exc).__name__}: {exc}"
            )
        else:
            self.signals.succeeded.emit(result)
        finally:
            self.signals.finished.emit()


class SweepDialog(QDialog):
    """Modal, responsive frequency-sweep controller."""

    def __init__(
        self,
        *,
        connection_parameters: dict[
            str,
            int | float,
        ],
        initial_frequency_hz: int,
        parent: QWidget | None = None,
    ):
        super().__init__(parent)

        self._connection_parameters = dict(
            connection_parameters
        )
        self._thread_pool = (
            QThreadPool.globalInstance()
        )

        self._control: SweepControl | None = None
        self._worker: SweepWorker | None = None
        self._running = False
        self._paused = False
        self._close_after_stop = False

        self.setWindowTitle(
            "OpenMoRFeus — Sweep Generator"
        )
        self.setMinimumSize(570, 500)
        self.setModal(True)

        self._build_interface()
        self._set_initial_frequency(
            initial_frequency_hz
        )
        self._update_summary()
        self._set_running_state(False)

    def _build_interface(self) -> None:
        root = QVBoxLayout(self)

        title = QLabel(
            "<h2>Sweep Generator</h2>"
            "<p>Verified frequency stepping with "
            "automatic restoration.</p>"
        )
        root.addWidget(title)

        self.plan_group = QGroupBox(
            "Sweep plan"
        )
        form = QFormLayout(self.plan_group)

        minimum_mhz = (
            MIN_FREQUENCY_HZ / 1_000_000
        )
        maximum_mhz = (
            MAX_FREQUENCY_HZ / 1_000_000
        )

        self.start_input = QDoubleSpinBox()
        self.start_input.setDecimals(6)
        self.start_input.setRange(
            minimum_mhz,
            maximum_mhz,
        )
        self.start_input.setSuffix(" MHz")
        self.start_input.setKeyboardTracking(False)
        form.addRow(
            "Start frequency:",
            self.start_input,
        )

        self.stop_input = QDoubleSpinBox()
        self.stop_input.setDecimals(6)
        self.stop_input.setRange(
            minimum_mhz,
            maximum_mhz,
        )
        self.stop_input.setSuffix(" MHz")
        self.stop_input.setKeyboardTracking(False)
        form.addRow(
            "Stop frequency:",
            self.stop_input,
        )

        self.step_input = QDoubleSpinBox()
        self.step_input.setDecimals(6)
        self.step_input.setRange(
            0.000001,
            maximum_mhz - minimum_mhz,
        )
        self.step_input.setValue(1.0)
        self.step_input.setSuffix(" MHz")
        self.step_input.setKeyboardTracking(False)
        form.addRow(
            "Step size:",
            self.step_input,
        )

        self.dwell_input = QSpinBox()
        self.dwell_input.setRange(
            0,
            3_600_000,
        )
        self.dwell_input.setValue(500)
        self.dwell_input.setSuffix(" ms")
        form.addRow(
            "Dwell time:",
            self.dwell_input,
        )

        self.restore_input = QCheckBox(
            "Restore initial frequency after "
            "completion, stop, or error"
        )
        self.restore_input.setChecked(True)
        form.addRow(
            "Safety:",
            self.restore_input,
        )

        root.addWidget(self.plan_group)

        summary_group = QGroupBox("Summary")
        summary_form = QFormLayout(
            summary_group
        )

        self.step_count_label = QLabel("—")
        summary_form.addRow(
            "Total frequencies:",
            self.step_count_label,
        )

        self.duration_label = QLabel("—")
        summary_form.addRow(
            "Minimum dwell duration:",
            self.duration_label,
        )

        root.addWidget(summary_group)

        progress_group = QGroupBox(
            "Execution"
        )
        progress_layout = QVBoxLayout(
            progress_group
        )

        self.progress_bar = QProgressBar()
        self.progress_bar.setRange(0, 1000)
        self.progress_bar.setValue(0)
        progress_layout.addWidget(
            self.progress_bar
        )

        progress_form = QFormLayout()

        self.current_frequency_label = QLabel(
            "—"
        )
        progress_form.addRow(
            "Current frequency:",
            self.current_frequency_label,
        )

        self.current_step_label = QLabel("—")
        progress_form.addRow(
            "Current step:",
            self.current_step_label,
        )

        self.status_label = QLabel("Ready")
        self.status_label.setWordWrap(True)
        progress_form.addRow(
            "Status:",
            self.status_label,
        )

        progress_layout.addLayout(
            progress_form
        )
        root.addWidget(progress_group)

        buttons = QHBoxLayout()

        self.start_button = QPushButton("Start")
        self.start_button.clicked.connect(
            self.start_sweep
        )
        buttons.addWidget(self.start_button)

        self.pause_button = QPushButton("Pause")
        self.pause_button.clicked.connect(
            self.pause_sweep
        )
        buttons.addWidget(self.pause_button)

        self.resume_button = QPushButton(
            "Resume"
        )
        self.resume_button.clicked.connect(
            self.resume_sweep
        )
        buttons.addWidget(self.resume_button)

        self.stop_button = QPushButton("Stop")
        self.stop_button.clicked.connect(
            self.stop_sweep
        )
        buttons.addWidget(self.stop_button)

        buttons.addStretch()

        self.close_button = QPushButton("Close")
        self.close_button.clicked.connect(
            self.close
        )
        buttons.addWidget(self.close_button)

        root.addLayout(buttons)

        for widget in (
            self.start_input,
            self.stop_input,
            self.step_input,
            self.dwell_input,
        ):
            widget.valueChanged.connect(
                self._update_summary
            )

    def _set_initial_frequency(
        self,
        frequency_hz: int,
    ) -> None:
        frequency_mhz = (
            frequency_hz / 1_000_000
        )

        minimum_mhz = (
            MIN_FREQUENCY_HZ / 1_000_000
        )
        maximum_mhz = (
            MAX_FREQUENCY_HZ / 1_000_000
        )

        frequency_mhz = min(
            max(frequency_mhz, minimum_mhz),
            maximum_mhz,
        )

        self.start_input.setValue(
            frequency_mhz
        )
        self.stop_input.setValue(
            min(
                frequency_mhz + 10.0,
                maximum_mhz,
            )
        )

    def _build_plan(self) -> SweepPlan:
        return SweepPlan(
            start_hz=round(
                self.start_input.value()
                * 1_000_000
            ),
            stop_hz=round(
                self.stop_input.value()
                * 1_000_000
            ),
            step_hz=round(
                self.step_input.value()
                * 1_000_000
            ),
            dwell_s=(
                self.dwell_input.value()
                / 1000.0
            ),
            restore_initial_frequency=(
                self.restore_input.isChecked()
            ),
        )

    def _update_summary(self) -> None:
        try:
            plan = self._build_plan()
        except (TypeError, ValueError) as exc:
            self.step_count_label.setText(
                "Invalid plan"
            )
            self.duration_label.setText("—")
            self.status_label.setText(str(exc))
            self.start_button.setEnabled(False)
            return

        self.step_count_label.setText(
            f"{plan.step_count:,}"
        )
        self.duration_label.setText(
            format_duration(
                plan.minimum_duration_s
            )
        )

        if not self._running:
            self.status_label.setText("Ready")
            self.start_button.setEnabled(True)

    def _set_running_state(
        self,
        running: bool,
    ) -> None:
        self._running = running

        self.plan_group.setEnabled(not running)
        self.start_button.setEnabled(not running)

        self.pause_button.setEnabled(
            running and not self._paused
        )
        self.resume_button.setEnabled(
            running and self._paused
        )
        self.stop_button.setEnabled(running)

    def start_sweep(self) -> None:
        if self._running:
            return

        try:
            plan = self._build_plan()
        except (TypeError, ValueError) as exc:
            QMessageBox.warning(
                self,
                "Invalid sweep plan",
                str(exc),
            )
            return

        if (
            not plan.restore_initial_frequency
            and QMessageBox.question(
                self,
                "Frequency restoration disabled",
                "The moRFeus will remain at the "
                "last sweep frequency. Continue?",
            )
            != QMessageBox.StandardButton.Yes
        ):
            return

        self.progress_bar.setValue(0)
        self.current_frequency_label.setText(
            "—"
        )
        self.current_step_label.setText(
            f"0 / {plan.step_count}"
        )
        self.status_label.setText(
            "Starting sweep…"
        )

        self._paused = False
        self._control = SweepControl()

        worker = SweepWorker(
            plan,
            self._connection_parameters,
            self._control,
        )
        self._worker = worker

        worker.signals.progress.connect(
            self._on_progress
        )
        worker.signals.succeeded.connect(
            self._on_succeeded
        )
        worker.signals.failed.connect(
            self._on_failed
        )
        worker.signals.finished.connect(
            self._on_finished
        )

        self._set_running_state(True)
        self._thread_pool.start(worker)

    def pause_sweep(self) -> None:
        if (
            not self._running
            or self._control is None
        ):
            return

        self._control.pause()
        self._paused = True
        self.status_label.setText("Paused")
        self._set_running_state(True)

    def resume_sweep(self) -> None:
        if (
            not self._running
            or self._control is None
        ):
            return

        self._control.resume()
        self._paused = False
        self.status_label.setText("Running")
        self._set_running_state(True)

    def stop_sweep(self) -> None:
        if (
            not self._running
            or self._control is None
        ):
            return

        self._control.stop()
        self.status_label.setText(
            "Stopping and restoring "
            "frequency…"
        )
        self.pause_button.setEnabled(False)
        self.resume_button.setEnabled(False)
        self.stop_button.setEnabled(False)

    def _on_progress(
        self,
        progress: SweepProgress,
    ) -> None:
        self.progress_bar.setValue(
            round(progress.percentage * 10)
        )
        self.current_frequency_label.setText(
            f"{progress.frequency_hz / 1_000_000:.6f} MHz"
        )
        self.current_step_label.setText(
            f"{progress.step_number} / "
            f"{progress.total_steps}"
        )

        if not self._paused:
            self.status_label.setText("Running")

    def _on_succeeded(
        self,
        result: SweepResult,
    ) -> None:
        if result.completed:
            outcome = "Sweep completed"
        elif result.stopped:
            outcome = "Sweep stopped"
        else:
            outcome = "Sweep interrupted"

        if (
            result.restored_initial_frequency
            or (
                result.initial_frequency_hz
                == result.last_sweep_frequency_hz
            )
        ):
            restoration = (
                "Initial frequency restored."
            )
        else:
            restoration = (
                "Final sweep frequency retained."
            )

        self.status_label.setText(
            f"{outcome}. {restoration} "
            f"Elapsed: "
            f"{format_duration(result.elapsed_s)}"
        )

    def _on_failed(self, message: str) -> None:
        self.status_label.setText(
            "Sweep failed"
        )

        QMessageBox.critical(
            self,
            "Sweep error",
            message,
        )

    def _on_finished(self) -> None:
        self._running = False
        self._paused = False
        self._control = None
        self._worker = None
        self._set_running_state(False)

        if self._close_after_stop:
            self._close_after_stop = False
            self.accept()

    def closeEvent(
        self,
        event: QCloseEvent,
    ) -> None:
        if (
            self._running
            and self._control is not None
        ):
            self._close_after_stop = True
            self._control.stop()
            self.status_label.setText(
                "Stopping before closing…"
            )
            event.ignore()
            return

        event.accept()
